version: "3.8"

services:
  # 1. Database MySQL
  mysql_restaurant:
    image: mysql:latest
    container_name: mysql_restaurant
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_restaurant
    ports:
      - "3306:3306"
    volumes:
      - mysql_restaurant_data:/var/lib/mysql
      - ./init/init_restaurant.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_user:
    image: mysql:latest
    container_name: mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_user
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
      - ./init/init_user.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_payment:
    image: mysql:latest
    container_name: mysql_payment
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_payment
    ports:
      - "3308:3306"
    volumes:
      - mysql_payment_data:/var/lib/mysql
      - ./init/init_payment.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_order:
    image: mysql:latest
    container_name: mysql_order
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_order
    ports:
      - "3309:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql
      - ./init/init_order.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Layanan API Gateway (Supergraph)
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - restaurant-service
      - payment-service
      - user-service

  # 3. Layanan Order
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - mysql_order

  # 4. Layanan Restaurant
  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "3001:3001"
    depends_on:
      - mysql_restaurant

  # 5. Layanan Payment
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3003:3003"
    depends_on:
      - mysql_payment

  # 6. Layanan User
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3004:3004"
    depends_on:
      - mysql_user

volumes:
  mysql_restaurant_data:
  mysql_user_data:
  mysql_payment_data:
  mysql_order_data:
